version: "3.8"
services:
  mysqldb:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    image: "mysql:8.0.33"
    restart: unless-stopped
    environment:
      "MYSQL_USER": admin
      "MYSQL_ROOT_PASSWORD": 1122
      "MYSQL_DATABASE": quest
      "MYSQL_PASSWORD": 1122
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  quest-service:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: /
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/quest?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1122
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_APPLICATION_NAME: quest-service
volumes:
  db: